import fs from "node:fs/promises";
import path from "node:path";

export async function writeGroqReports(run) {
  const evidence = await collectEvidence(run);
  const fallback = fallbackReports(run, evidence);

  if (!process.env.GROQ_API_KEY) {
    await writeReports(run, fallback, "GROQ_API_KEY is missing; wrote deterministic evidence reports.");
    return { usedGroq: false, output: "GROQ_API_KEY is missing; deterministic reports written." };
  }

  try {
    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${process.env.GROQ_API_KEY}`
      },
      body: JSON.stringify({
        model: process.env.GROQ_MODEL || "llama-3.3-70b-versatile",
        temperature: 0.7,
        messages: [
          {
            role: "system",
            content: "You write evidence-grounded technical case files. You may use noir investigation flavor, but you must not invent technical facts. Distinguish source facts, Kiro work, Lark evidence, and caveats."
          },
          {
            role: "user",
            content: reportPrompt(run, evidence)
          }
        ]
      })
    });

    if (!response.ok) {
      const text = await response.text();
      await writeReports(run, fallback, `Groq request failed with HTTP ${response.status}: ${text}`);
      return { usedGroq: false, output: `Groq request failed with HTTP ${response.status}. Deterministic reports written.` };
    }

    const json = await response.json();
    const content = json.choices?.[0]?.message?.content || "";
    const reports = splitReports(content, fallback);
    await writeReports(run, reports, "Generated by Groq from collected evidence.");
    return { usedGroq: true, output: "Groq reports written." };
  } catch (error) {
    await writeReports(run, fallback, error.stack || error.message);
    return { usedGroq: false, output: `Groq failed; deterministic reports written. ${error.message}` };
  }
}

async function collectEvidence(run) {
  const readMaybe = async (relative) => {
    try {
      return await fs.readFile(path.join(run.workspaceDir, relative), "utf8");
    } catch {
      return "";
    }
  };

  return {
    original: truncateEvidence(await readMaybe("original/original-question.md")),
    technical: truncateEvidence(await readMaybe("reports/technical-report.md")),
    kiro: truncateEvidence(await readMaybe("logs/kiro.log")),
    lark: truncateEvidence(await readMaybe("logs/lark.log"), 5000),
    publish: truncateEvidence(await readMaybe("logs/github.log"), 2500)
  };
}

function truncateEvidence(value, maxChars = 3500) {
  const text = String(value || "");
  if (text.length <= maxChars) return text;
  const head = text.slice(0, Math.floor(maxChars * 0.65));
  const tail = text.slice(-Math.floor(maxChars * 0.35));
  return `${head}\n\n[...truncated for Groq token budget...]\n\n${tail}`;
}

function reportPrompt(run, evidence) {
  return `Create three Markdown reports for this Coding Cold Cases Cracker run.

Required delimiters:
---TECHNICAL-REPORT---
---CASE-FILE---
---JUDGE-SUMMARY---

Case state:
${JSON.stringify(run, null, 2)}

Evidence:
${JSON.stringify(evidence, null, 2)}

Rules:
- Do not claim Closed unless Lark verification passed in the state.
- Include sections: Case Summary, Original Clue, Reproduction Lab, Lark's First Finding, Root Cause, The Fix, Lark Verification, Confidence And Caveats, Replay Commands, Artifact Links.
- Keep the case file memorable but technically responsible.
`;
}

function splitReports(content, fallback) {
  const technical = between(content, "---TECHNICAL-REPORT---", "---CASE-FILE---") || fallback.technical;
  const caseFile = between(content, "---CASE-FILE---", "---JUDGE-SUMMARY---") || fallback.caseFile;
  const judge = content.includes("---JUDGE-SUMMARY---") ? content.split("---JUDGE-SUMMARY---").pop().trim() : fallback.judge;
  return { technical, caseFile, judge };
}

function between(value, start, end) {
  const startIndex = value.indexOf(start);
  const endIndex = value.indexOf(end);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return "";
  return value.slice(startIndex + start.length, endIndex).trim();
}

async function writeReports(run, reports, note) {
  await fs.writeFile(path.join(run.workspaceDir, "reports", "technical-report.md"), ensureTitle(reports.technical, "Technical Report"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "case-file.md"), ensureTitle(reports.caseFile, "Case File"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "judge-summary.md"), ensureTitle(reports.judge, "Judge Summary"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "writer-note.md"), `# Writer Note\n\n${note}\n`);
}

function fallbackReports(run, evidence) {
  const status = run.status;
  const larkStatus = run.lark?.verification_passed ? "Lark verification passed." : "Lark verification has not passed.";
  const base = `# ${run.original.title}

## Case Summary

This run investigated ${run.original.url} as a support incident reproduction case.

## Original Clue

${run.original.why_interesting || "See original question artifact."}

## Reproduction Lab

Status: ${status}

## Lark's First Finding

${evidence.lark || "No Lark log has been captured yet."}

## Root Cause

${evidence.technical || "Root cause is pending Kiro investigation."}

## The Fix

See repaired workspace and technical report when available.

## Lark Verification

${larkStatus}

## Confidence And Caveats

This report is generated from currently available artifacts only.

## Replay Commands

- Reproduce: ${run.commands?.reproduce || "pending"}
- Verify: ${run.commands?.verify || "pending"}

## Artifact Links

- Workspace: ${run.workspace}
- Remote: ${run.github?.remote_url || "not published"}
`;
  return {
    technical: base,
    caseFile: `${base}\n\n## Narrative\n\nThe case remains on the board until Lark's evidence closes it.\n`,
    judge: `# Judge Summary\n\n${run.original.title}\n\nStatus: ${status}\n\n${larkStatus}\n`
  };
}

function ensureTitle(value, title) {
  const trimmed = String(value || "").trim();
  if (trimmed.startsWith("#")) return `${trimmed}\n`;
  return `# ${title}\n\n${trimmed}\n`;
}
