import fs from "node:fs/promises";
import path from "node:path";
import { generateKiroWriterPrompt, runKiroPhase } from "./kiro.js";

export async function writeCaseReports(run) {
  const evidence = await collectEvidence(run);
  const fallback = fallbackReports(run, evidence, "Creative writer was not available.");
  let lastIssue = "Kiro writer did not return an acceptable creative case file.";

  for (let attempt = 1; attempt <= 2; attempt += 1) {
    await generateKiroWriterPrompt(run, evidence, { strict: attempt > 1 });
    const kiro = await runKiroPhase(run, "writer");
    await fs.appendFile(path.join(run.workspaceDir, "logs", "kiro-writer.log"), `${kiro.output}\n`);

    if (kiro.code !== 0) {
      lastIssue = kiro.output || `Kiro writer exited with code ${kiro.code}.`;
      if (kiro.mode === "interactive-required") break;
      continue;
    }

    const reports = await readGeneratedReports(run, fallback);
    const quality = evaluateCaseFile(reports.caseFile, run);
    if (quality.accepted) {
      await writeWriterNote(run, `Generated by Kiro case-writer on attempt ${attempt}.`, {
        ...quality,
        attempts: attempt
      });
      return {
        usedKiroWriter: true,
        output: "Kiro creative reports written.",
        quality: { ...quality, attempts: attempt }
      };
    }
    lastIssue = quality.issues.join("; ");
  }

  const rejected = fallbackReports(run, evidence, `Creative writer failed quality gates: ${lastIssue}`);
  await writeReports(run, rejected, `Creative writer failed quality gates: ${lastIssue}`, {
    accepted: false,
    attempts: 2,
    issues: [lastIssue]
  });
  return {
    usedKiroWriter: false,
    output: `Kiro writer output rejected; deterministic fallback written. ${lastIssue}`,
    quality: { accepted: false, attempts: 2, issues: [lastIssue] }
  };
}

async function collectEvidence(run) {
  const readMaybe = async (relative, maxChars = 3500) => {
    try {
      return truncateEvidence(await fs.readFile(path.join(run.workspaceDir, relative), "utf8"), maxChars);
    } catch {
      return "";
    }
  };

  return {
    original: await readMaybe("original/original-question.md", 2600),
    reconstruction: await readMaybe("reports/reconstruction-report.md", 2200),
    technical: await readMaybe("reports/technical-report.md", 2200),
    kiroReconstruction: await readMaybe("logs/kiro-reconstruction.log", 1600),
    kiroRepair: await readMaybe("logs/kiro-repair.log", 1600),
    larkReproduction: await readMaybe("lark/reproduction-output.md", 2600),
    larkReproductionEvidence: await readMaybe("lark/reproduction-evidence.json", 1800),
    larkVerification: await readMaybe("lark/verification-output.md", 2600),
    larkVerificationEvidence: await readMaybe("lark/verification-evidence.json", 1800),
    publish: await readMaybe("logs/github.log", 1000),
    styleBrief: [
      "Style target: noir-tinged literary technical fiction about a real debugging mystery.",
      "Open with a human developer in a concrete scene, with enough personality, pressure, and sensory detail that the case feels lived in.",
      "Let the technical failure appear as dramatic conflict, then introduce the combined Kiro/Lark system as Larkule Quirot, a meticulous debugging detective.",
      "Use original imagery and phrasing. Do not copy any reference example text."
    ].join(" ")
  };
}

function truncateEvidence(value, maxChars = 3500) {
  const text = String(value || "");
  if (text.length <= maxChars) return text;
  const head = text.slice(0, Math.floor(maxChars * 0.65));
  const tail = text.slice(-Math.floor(maxChars * 0.35));
  return `${head}\n\n[...truncated for writer prompt budget...]\n\n${tail}`;
}

async function readGeneratedReports(run, fallback) {
  const readMaybe = async (relative, fallbackValue) => {
    try {
      return await fs.readFile(path.join(run.workspaceDir, relative), "utf8");
    } catch {
      return fallbackValue;
    }
  };
  const evidenceMap = await readEvidenceMap(path.join(run.workspaceDir, "reports", "evidence-map.json"), fallback.evidenceMap);
  return {
    technical: await readMaybe("reports/technical-report.md", fallback.technical),
    caseFile: await readMaybe("reports/case-file.md", fallback.caseFile),
    user: await readMaybe("reports/user-summary.md", fallback.user),
    evidenceMap
  };
}

async function readEvidenceMap(filePath, fallback) {
  try {
    const value = JSON.parse(await fs.readFile(filePath, "utf8"));
    if (Array.isArray(value.claims) && Array.isArray(value.artifacts)) return value;
    return { ...fallback, parse_error: "Evidence map JSON did not have claims/artifacts arrays." };
  } catch {
    return fallback;
  }
}

function evaluateCaseFile(caseFile, run = {}) {
  const issues = [];
  const text = String(caseFile || "").trim();
  const normalized = text.toLowerCase();
  const body = text.replace(/^#.*$/m, "").trim();
  const paragraphs = body.split(/\n\s*\n/).map((part) => part.trim()).filter(Boolean);

  if (/^#?\s*(case summary|original clue|reproduction lab|root cause|technical report)\b/i.test(body)) {
    issues.push("case file starts with report language");
  }
  if (/the interrogation began|not officially, of course|technological siege warfare|maven never screamed|pale blue light of accumulated regret|lying face-down like a murder victim/i.test(text)) {
    issues.push("case file reuses distinctive wording from the reference example");
  }
  if (/###?\s*User Summary/i.test(text)) {
    issues.push("case file contains summary content");
  }
  if (/\btypical monday morning\b|\bhours ticked by\b|\bdebugging tools like Kiro and Lark\b/i.test(text)) {
    issues.push("case file uses generic narrative filler");
  }
  if (text.split(/\s+/).filter(Boolean).length < 750) {
    issues.push("case file is too short for the requested creative narrative");
  }
  if (paragraphs.length < 8) {
    issues.push("case file is too short to read like a narrative");
  }
  if (!/(lark).{0,80}(finding|evidence|forensic|verdict|verification)|(?:finding|evidence|forensic|verdict|verification).{0,80}(lark)/is.test(text)) {
    issues.push("case file does not clearly include Lark's finding or verdict");
  }
  if (!/larkule\s+quirot/i.test(text)) {
    issues.push("case file does not use Larkule Quirot as the combined investigator persona");
  }
  if (run.original?.owner?.display_name && !text.includes(String(run.original.owner.display_name))) {
    issues.push("case file does not use the exact original Stack Overflow poster handle/display name");
  }
  if (!/(noir|shadow|rain|cigarette|lamp|alley|case|detective|clue|suspect|verdict|interrogat|evidence|trail|mystery|office|night|fog|flicker|hum)/i.test(text)) {
    issues.push("case file lacks mystery/noir atmosphere");
  }
  if (!/(smiled|sighed|muttered|whispered|laughed|grimaced|stared|rubbed|tapped|paced|coffee|tea|collar|sleeves|desk|chair|window|kitchen|apartment|office)/i.test(paragraphs.slice(0, 10).join(" "))) {
    issues.push("opening lacks character personality and human scene texture");
  }
  if (/(kiro).{0,90}(lark)|(?:lark).{0,90}(kiro)/is.test(paragraphs.slice(0, 12).join(" "))) {
    issues.push("opening separates Kiro and Lark before establishing Larkule Quirot");
  }
  if (!/(apartment|office|monitor|keyboard|terminal|screen|night|morning|developer|engineer|coffee|build|error|question|stackoverflow|repository|incident|console)/i.test(paragraphs.slice(0, 6).join(" "))) {
    issues.push("opening does not establish scene, character, conflict, and technical mystery");
  }
  const reportHeadingCount = (text.match(/^##\s+(Case Summary|Original Clue|Reproduction Lab|Root Cause|The Fix|Lark Verification|Confidence And Caveats)/gim) || []).length;
  if (reportHeadingCount >= 3) {
    issues.push("case file reads like a templated technical report");
  }
  if (normalized.includes("lorem ipsum") || normalized.includes("placeholder")) {
    issues.push("case file contains placeholder text");
  }

  return { accepted: issues.length === 0, issues };
}

async function writeReports(run, reports, note, quality) {
  await fs.mkdir(path.join(run.workspaceDir, "reports"), { recursive: true });
  await fs.writeFile(path.join(run.workspaceDir, "reports", "technical-report.md"), ensureTitle(reports.technical, "Technical Report"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "case-file.md"), ensureTitle(reports.caseFile, "Case File"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "user-summary.md"), ensureTitle(reports.user, "User Summary"));
  await fs.writeFile(path.join(run.workspaceDir, "reports", "evidence-map.json"), `${JSON.stringify(reports.evidenceMap || { claims: [], artifacts: [] }, null, 2)}\n`);
  await writeWriterNote(run, note, quality);
}

async function writeWriterNote(run, note, quality) {
  await fs.mkdir(path.join(run.workspaceDir, "reports"), { recursive: true });
  await fs.writeFile(path.join(run.workspaceDir, "reports", "writer-note.md"), `# Writer Note\n\n${note}\n\nProvider: Kiro CLI case-writer\n\nQuality:\n\n\`\`\`json\n${JSON.stringify(quality, null, 2)}\n\`\`\`\n`);
}

function fallbackReports(run, evidence, reason) {
  const status = run.status;
  const larkStatus = run.lark?.verification_passed ? "Lark verification passed." : "Lark verification has not passed.";
  const technical = `# ${run.original.title}

## Technical Evidence

This run investigated ${run.original.url} as a support incident reproduction case.

Status: ${status}

## Original Clue

${run.original.why_interesting || "See original question artifact."}

## Reconstruction

${evidence.reconstruction || "Reconstruction report is pending."}

## Lark Reproduction Evidence

${evidence.larkReproductionEvidence || evidence.larkReproduction || "No Lark reproduction evidence has been captured yet."}

## Repair

${evidence.technical || "Repair report is pending."}

## Lark Verification

${evidence.larkVerificationEvidence || evidence.larkVerification || larkStatus}

## Replay Commands

- Reproduce: ${run.commands?.reproduce || "pending"}
- Verify: ${run.commands?.verify || "pending"}
`;

  const caseFile = `# ${run.original.title}

The case file is pending a clean narrative pass.

The evidence desk has preserved the original question, the reconstruction trail, the forensic outputs, and the repair notes that exist so far. This file is intentionally sparse so a writer failure is not blended into the final case narrative. See \`reports/writer-note.md\` for the retry record and failure details.

Lark status: ${larkStatus}

## Factual Replay Appendix

- Reproduce: ${run.commands?.reproduce || "pending"}
- Verify: ${run.commands?.verify || "pending"}
- Workspace: ${run.workspace}
- Remote: ${run.github?.remote_url || "not published"}
`;

  return {
    technical,
    caseFile,
    user: `# User Summary

${run.original.title}

Status: ${status}

Why Lark mattered: ${larkStatus} Lark is the closure gate and its reproduction/verification artifacts are preserved under \`lark/\`.
`,
    evidenceMap: {
      claims: [
        { claim: "Original case source", artifact: "original/original-question.md" },
        { claim: "Kiro reconstruction", artifact: "reports/reconstruction-report.md" },
        { claim: "Lark reproduction evidence", artifact: "lark/reproduction-evidence.json" },
        { claim: "Lark verification evidence", artifact: "lark/verification-evidence.json" }
      ],
      artifacts: [
        "original/original-question.md",
        "reports/reconstruction-report.md",
        "reports/technical-report.md",
        "lark/reproduction-evidence.json",
        "lark/verification-evidence.json"
      ]
    }
  };
}

function ensureTitle(value, title) {
  const trimmed = String(value || "").trim();
  if (trimmed.startsWith("#")) return `${trimmed}\n`;
  return `# ${title}\n\n${trimmed}\n`;
}
